### ISSUE TITLE
Add Redox OS

### ISSUE THREAD

**Issue by Siilwyn** [schultyy/os_type#11]
Hi there I'm thinking of creating a PR to add [Redox](http://www.redox-os.org/), found it fitting to include this since it's made in Rust too.

Thoughts?

**Comment by schultyy** [comment]
Sounds good, go ahead 👍

**Comment by Siilwyn** [comment]
Nice! Heh, I wrote it a bit too positive though because I have to figure out how to get Redox running and I'm a beginner when it comes to Rust. So if anybody reads this and knows how to tackle this issue please ping me, would love to do some pair programming.
