### ISSUE TITLE
Add OS Version?

### ISSUE THREAD

**Issue by drusellers** [schultyy/os_type#12]

**Comment by schultyy** [comment]
@drusellers Hi, do you have thoughts on how the OS Version should be made available?

**Comment by drusellers** [comment]
I'm just starting to dig into linux land, so I'm at a bit of a loss - but I've been toying with `uname` but my guess is that may not be the best way. Hmm

**Comment by drusellers** [comment]
`lsb_release -r` / `lsb_release -a` if its available is nice. I'm assuming you want to support multiple OS's so I'm guessing we will need to have a few different branches. On windows one way is `ver` for CMD - and Powershell (using WMI) `(Get-CimInstance Win32_OperatingSystem).version`

**Comment by schultyy** [comment]
Version 1.0.0 now has version support included :tada: 
Unfortunately I had to pull out Windows though because I don't have any Windows machine at hand to test this properly.
